### ISSUE TITLE
[Suggestion] Mooblooms should produce suspicious stew when milked.

### ISSUE THREAD

**Issue by IndiePhunq** [Yanis48/Mooblooms#1]
Since mooshrooms produce mushroom stew when milked, it's logical that mooblooms would produce suspicious stew. For example, poppy mooblooms would produce a night vision suspicious stew, because suspicious stew made with poppies induces night vision.

**Comment by Yanis48** [comment]
That's actually a pretty good idea, going to implement that :)
Thanks for the suggestion!

**Comment by Yanis48** [comment]
Now implemented
