### ISSUE TITLE
wither chickens

### ISSUE THREAD

**Issue by Worgrick** [Yanis48/Mooblooms#6]
There is no way to get feathers in the nether currently, but wither chickens would be a way.

**Comment by Worgrick** [comment]
if you could implement like with wither mooblooms and cluckshrooms that would be awesome thanks for checking out my idea.

**Comment by Yanis48** [comment]
What about cluckshrooms with other types of mushrooms and fungi? I think it would fit better

**Comment by Worgrick** [comment]
You already have an array of mooblooms, I dont see why not, it's just that while exploring the nether I ran into wither cows, hadn't run into the the other two yet but that was probably because I was not in the right biome. I guess it depends on how much you want to do.

**Comment by Worgrick** [comment]
I've made a kitchen sink type mod pack using your mod, mostly for personal use but if you want I can send a zip file for fabric snapshot w19, it would literally be a list of mods from forge. To play you would put it in the mods folder. Anyway just an offer I think its alot of fun especially when you start in the nether.

**Comment by Worgrick** [comment]
It might give you an idea what I'm using your mod for at least.😁👍

**Comment by Yanis48** [comment]
I feel like people will ask me to add chickens for all flowers if I add a wither one ^^
Anyway I actually think I will add crimson and warped cluckshrooms in the Nether to make feathers available, as you said, so thanks for the idea :)
Just so you know, in 1.3.0 the mod will provide a very simple API to add mooblooms and cluckshrooms :)

**Comment by Worgrick** [comment]
Nice, that would make it so that I dont have to make a chicken jockey farm. Hey let me know how/if you want me to send the zip file.😄

**Comment by Yanis48** [comment]
About the modpack, yes you can send it if you want, I would be glad to test it :)

**Comment by Worgrick** [comment]
Currently its 38,045 KB, if you can't run that I can make a lite version, if your cool with that size tell me how I should send it to you please.

**Comment by Yanis48** [comment]
New cluckshrooms added in 1.3.0
